### ISSUE TITLE
Implement proper nickname checks on "nickchange" (and configuration option "nickname")

### ISSUE THREAD

**Issue by avail** [icedream/ts3bot-control#14]
changenick command won't return anything if the nickname is too short or long for it to set.

**Comment by avail** [comment]
Also need to add a check for whether the nick is invalid (contains characters teamspeak doesn't like)

**Comment by icedream** [comment]
I added the configuration option "nickname" here as well for convenience. Shouldn't be hard to copypaste or reuse code for this.
